/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MediaType = { 'video' : null } |
  { 'image' : null };
export interface Post {
  'id' : string,
  'createdAt' : bigint,
  'mediaUrl' : string,
  'creatorPrincipal' : Principal,
  'caption' : string,
  'mediaType' : MediaType,
  'commentsCount' : bigint,
  'likesCount' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'country' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'role' : UserRole,
  'coinsBalance' : bigint,
  'avatarUrl' : string,
  'followingCount' : bigint,
}
export type UserRole = { 'creator' : null } |
  { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createPost' : ActorMethod<[string, string, MediaType], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPostsByCreator' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string, string, UserRole], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'updateMyProfile' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];