/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'creator' : IDL.Null,
  'admin' : IDL.Null,
  'user' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'country' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'coinsBalance' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'followingCount' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'mediaUrl' : IDL.Text,
  'creatorPrincipal' : IDL.Principal,
  'caption' : IDL.Text,
  'mediaType' : MediaType,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, MediaType], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getPostsByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const UserRole = IDL.Variant({
    'creator' : IDL.Null,
    'admin' : IDL.Null,
    'user' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'country' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'coinsBalance' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'followingCount' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'mediaUrl' : IDL.Text,
    'creatorPrincipal' : IDL.Principal,
    'caption' : IDL.Text,
    'mediaType' : MediaType,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, MediaType], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getPostsByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };